CREATE DATABASE IF NOT EXISTS TODO;

use TODO;

CREATE Table IF NOT EXISTS USERS (
    email VARCHAR(50) not null PRIMARY KEY,
    nome VARCHAR(50) not NULL,
    senha VARCHAR(50) not NULL
);

CREATE TABLE IF NOT EXISTS TASKS (
    id int AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email_user VARCHAR(50) NOT NULL,
    descricao VARCHAR(50),
    FOREIGN KEY (email_user) REFERENCES USERS(email)
);


DROP TABLE TASKS